import './globals.css'
import { Inter } from 'next/font/google'
import { Navbar } from '@/components/common/Navbar'
const inter = Inter({ subsets: ['latin'] })
import { ToastContainer } from 'react-toastify';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="min-h-screen items-center p-2 md:p-24">
          {children}
        </main >
        <ToastContainer
          position="bottom-right"
          autoClose={1500}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light" />
      </body>
    </html>
  )
}
